'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('city',
      [

        { description:'Arroio do Meio', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cruzeiro do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Lajeado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Marques de Souza', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Aceguá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Água Santa', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Agudo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ajuricaba', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Alecrim', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Alegrete', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Alegria', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Almirante Tamandaré do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Alpestre', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Alto Alegre', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Alto Feliz', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Alvorada', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Amaral Ferrador', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ametista do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'André da Rocha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Anta Gorda', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Antônio Prado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Arambaré', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Araricá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Aratiba', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Arroio do Meio', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Arroio do Padre', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Arroio do Sal', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Arroio do Tigre', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Arroio dos Ratos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Arroio Grande', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Arvorezinha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Augusto Pestana', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Áurea', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Bagé', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Balneário Pinhal', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Barão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Barão de Cotegipe', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Barão do Triunfo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Barra do Guarita', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Barra do Quaraí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Barra do Ribeiro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Barra do Rio Azul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Barra Funda', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Barracão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Barros Cassal', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Benjamin Constant do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Bento Gonçalves', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Boa Vista das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Boa Vista do Buricá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Boa Vista do Cadeado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Boa Vista do Incra', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Boa Vista do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Bom Jesus', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Bom Princípio', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Bom Progresso', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Bom Retiro do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Boqueirão do Leão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Bossoroca', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Bozano', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Braga', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Brochier', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Butiá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Caçapava do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cacequi', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cachoeira do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cachoeirinha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cacique Doble', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Caibaté', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Caiçara', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Camaquã', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Camargo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cambará do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Campestre da Serra', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Campina das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Campinas do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Campo Bom', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Campo Novo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Campos Borges', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Candelária', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cândido Godói', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Candiota', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Canela', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Canguçu', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Canoas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Canudos do Vale', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Capão Bonito do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Capão da Canoa', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Capão do Cipó', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Capão do Leão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Capela de Santana', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Capitão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Capivari do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Caraá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Carazinho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Carlos Barbosa', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Carlos Gomes', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Casca', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Caseiros', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Catuípe', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Caxias do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Centenário', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cerrito', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cerro Branco', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cerro Grande', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cerro Grande do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cerro Largo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Chapada', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Charqueadas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Charrua', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Chiapetta', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Chuí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Chuvisca', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cidreira', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ciríaco', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Colinas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Colorado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Condor', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Constantina', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Coqueiro Baixo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Coqueiros do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Coronel Barros', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Coronel Bicaco', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Coronel Pilar', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cotiporã', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Coxilha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Crissiumal', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cristal', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cristal do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cruz Alta', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cruzaltense', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Cruzeiro do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'David Canabarro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Derrubadas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Dezesseis de Novembro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Dilermando de Aguiar', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Dois Irmãos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Dois Irmãos das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Dois Lajeados', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Dom Feliciano', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Dom Pedrito', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Dom Pedro de Alcântara', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Dona Francisca', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Doutor Maurício Cardoso', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Doutor Ricardo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Eldorado do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Encantado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Encruzilhada do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Engenho Velho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Entre Rios do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Entre-Ijuís', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Erebango', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Erechim', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ernestina', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Erval Grande', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Erval Seco', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Esmeralda', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Esperança do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Espumoso', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Estação', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Estância Velha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Esteio', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Estrela', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Estrela Velha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Eugênio de Castro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Fagundes Varela', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Farroupilha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Faxinal do Soturno', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Faxinalzinho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Fazenda Vilanova', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Feliz', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Flores da Cunha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Floriano Peixoto', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Fontoura Xavier', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Formigueiro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Forquetinha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Fortaleza dos Valos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Frederico Westphalen', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Garibaldi', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Garruchos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Gaurama', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'General Câmara', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Gentil', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Getúlio Vargas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Giruá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Glorinha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Gramado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Gramado dos Loureiros', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Gramado Xavier', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Gravataí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Guabiju', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Guaíba', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Guaporé', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Guarani das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Harmonia', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Herval', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Herveiras', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Horizontina', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Hulha Negra', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Humaitá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ibarama', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ibiaçá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ibiraiaras', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ibirapuitã', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ibirubá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Igrejinha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ijuí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ilópolis', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Imbé', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Imigrante', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Independência', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Inhacorá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ipê', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ipiranga do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Iraí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Itaara', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Itacurubi', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Itapuca', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Itaqui', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Itati', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Itatiba do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ivorá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ivoti', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Jaboticaba', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Jacuizinho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Jacutinga', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Jaguarão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Jaguari', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Jaquirana', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Jari', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Jóia', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Júlio de Castilhos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Lagoa Bonita do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Lagoa dos Três Cantos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Lagoa Vermelha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Lagoão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Lajeado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Lajeado do Bugre', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Lavras do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Liberato Salzano', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Lindolfo Collor', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Linha Nova', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Maçambara', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Machadinho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Mampituba', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Manoel Viana', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Maquiné', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Maratá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Marau', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Marcelino Ramos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Mariana Pimentel', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Mariano Moro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Marques de Souza', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Mata', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Mato Castelhano', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Mato Leitão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Mato Queimado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Maximiliano de Almeida', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Minas do Leão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Miraguaí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Montauri', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Monte Alegre dos Campos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Monte Belo do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Montenegro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Mormaço', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Morrinhos do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Morro Redondo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Morro Reuter', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Mostardas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Muçum', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Muitos Capões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Muliterno', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Não-Me-Toque', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nicolau Vergueiro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nonoai', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Alvorada', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Araçá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Bassano', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Boa Vista', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Bréscia', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Candelária', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Esperança do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Hartz', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Pádua', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Palma', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Petrópolis', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Prata', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Ramada', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Roma do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Nova Santa Rita', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Novo Barreiro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Novo Cabrais', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Novo Hamburgo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Novo Machado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Novo Tiradentes', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Novo Xingu', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Osório', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Paim Filho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Palmares do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Palmeira das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Palmitinho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Panambi', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pantano Grande', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Paraí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Paraíso do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pareci Novo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Parobé', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Passa Sete', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Passo do Sobrado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Passo Fundo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Paulo Bento', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Paverama', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pedras Altas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pedro Osório', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pejuçara', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pelotas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Picada Café', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pinhal', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pinhal da Serra', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pinhal Grande', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pinheirinho do Vale', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pinheiro Machado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pirapó', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Piratini', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Planalto', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Poço das Antas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pontão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ponte Preta', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Portão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Porto Alegre', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Porto Lucena', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Porto Mauá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Porto Vera Cruz', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Porto Xavier', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Pouso Novo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Presidente Lucena', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Progresso', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Protásio Alves', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Putinga', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Quaraí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Quatro Irmãos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Quevedos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Quinze de Novembro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Redentora', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Relvado', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Restinga Seca', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Rio dos Índios', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Rio Grande', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Rio Pardo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Riozinho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Roca Sales', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Rodeio Bonito', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Rolador', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Rolante', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ronda Alta', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Rondinha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Roque Gonzales', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Rosário do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sagrada Família', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Saldanha Marinho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Salto do Jacuí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Salvador das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Salvador do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sananduva', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santa Bárbara do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santa Cecília do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santa Clara do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santa Cruz do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santa Margarida do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santa Maria', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santa Maria do Herval', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santa Rosa', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santa Tereza', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santa Vitória do Palmar', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santana da Boa Vista', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santana do Livramento', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santiago', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santo  ngelo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santo Antônio da Patrulha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santo Antônio das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santo Antônio do Palma', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santo Antônio do Planalto', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santo Augusto', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santo Cristo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Santo Expedito do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Borja', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Domingos do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Francisco de Assis', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Francisco de Paula', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Gabriel', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Jerônimo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São João da Urtiga', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São João do Polêsine', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Jorge', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São José das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São José do Herval', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São José do Hortêncio', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São José do Inhacorá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São José do Norte', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São José do Ouro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São José do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São José dos Ausentes', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Leopoldo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Lourenço do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Luiz Gonzaga', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Marcos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Martinho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Martinho da Serra', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Miguel das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Nicolau', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Paulo das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Pedro da Serra', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Pedro das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Pedro do Butiá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Pedro do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Sebastião do Caí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Sepé', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Valentim', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Valentim do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Valério do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Vendelino', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'São Vicente do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sapiranga', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sapucaia do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sarandi', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Seberi', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sede Nova', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Segredo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Selbach', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Senador Salgado Filho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sentinela do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Serafina Corrêa', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sério', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sertão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sertão Santana', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sete de Setembro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Severiano de Almeida', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Silveira Martins', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sinimbu', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Sobradinho', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Soledade', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tabaí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tapejara', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tapera', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tapes', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Taquara', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Taquari', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Taquaruçu do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tavares', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tenente Portela', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Terra de Areia', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Teutônia', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tio Hugo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tiradentes do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Toropi', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Torres', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tramandaí', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Travesseiro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Três Arroios', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Três Cachoeiras', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Três Coroas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Três de Maio', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Três Forquilhas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Três Palmeiras', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Três Passos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Trindade do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Triunfo', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tucunduva', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tunas', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tupanci do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tupanciretã', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tupandi', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Tuparendi', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Turuçu', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Ubiretama', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'União da Serra', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Unistalda', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Uruguaiana', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vacaria', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vale do Sol', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vale Real', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vale Verde', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vanini', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Venâncio Aires', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vera Cruz', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Veranópolis', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vespasiano Correa', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Viadutos', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Viamão', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vicente Dutra', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Victor Graeff', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vila Flores', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vila Lângaro', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vila Maria', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vila Nova do Sul', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vista Alegre', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vista Alegre do Prata', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vista Gaúcha', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Vitória das Missões', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Westfalia', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },
        { description:'Xangri-lá', uf:'RS', state:'Rio Grande do Sul', created_at: new Date(), updated_at: new Date() },        
      ], {}
  ),
  down: (queryInterface) => queryInterface.bulkDelete('city', null, {})
};
